# Generated by Django 3.1.3 on 2020-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20201110_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='hero_headshots/'),
        ),
    ]
